name: action-TIL-Serve

on:
  push:
    branches: 
      - action, main

jobs:
  build:
    runs-on: ubuntu latest
  
   
    steps:
     - name: Checkout
       uses: actions/checkout@v3.5.2
       
     - name: Http Server
       uses: Eun/http-server-action@v1.0.6
